"""
MODULE 3 EXERCISE: Multi-Branch Composition using LCEL.

Goal:
Create a branching pipeline that takes a single book 'topic', generates a title,
and then generates both a chapter outline and a marketing hook concurrently.

Pipeline DAG:
             topic
               │
               ▼
          [Book Title]
         /            \
        ▼              ▼
   [Chapter Index]   [Marketing Hook]
        \              /
         ▼            ▼
     [Inject Disclaimer to both outputs]
"""

import os
import sys
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableParallel, RunnableLambda

load_dotenv()

# Step 1: Initialize model
api_key = os.getenv("OPENROUTER_API_KEY")
if not api_key:
    print("ERROR: Please define OPENROUTER_API_KEY in your .env file.")
    sys.exit(1)

model = ChatOpenAI(
    openai_api_base="https://openrouter.ai/api/v1",
    openai_api_key=api_key,
    model_name="google/gemma-2-9b-it:free",
    temperature=0.7,
)

# Step 2: Build the title generation step
title_prompt = ChatPromptTemplate.from_template("Generate a creative book title for a book about: {topic}")
# TODO: Create the title_chain (hint: title_prompt | model | StrOutputParser)
title_chain = None

# Step 3: Build the parallel branches
# These prompts will consume the generated title (passed as variable 'title')
outline_prompt = ChatPromptTemplate.from_template("Create a brief 3-chapter outline for the book titled: '{title}'")
marketing_prompt = ChatPromptTemplate.from_template("Write a one-sentence sales pitch targeting college students for the book: '{title}'")

# TODO: Create outline_chain and marketing_chain
outline_chain = None
marketing_chain = None

# TODO: Combine them into a RunnableParallel block
# Hint: RunnableParallel(key1=chain1, key2=chain2)
parallel_branches = None

# Step 4: Write a python function to inject a disclaimer string at the end of the values
# The function will take a dict like: {'outline': '...', 'pitch': '...'}
# and append "\n\n[Generated by AI]" to both string values.
# TODO: Complete the python function
def add_disclaimer(inputs: dict) -> dict:
    # inputs['outline'] = ...
    # inputs['pitch'] = ...
    return inputs

# Wrap it in RunnableLambda
disclaimer_runnable = RunnableLambda(add_disclaimer)

# Step 5: Assemble the complete LCEL sequence
# Dynamic flow:
# 1. Takes 'topic' -> returns {'title': title_chain}
# 2. Feeds {'title': title} -> parallel_branches (returning {'outline': ..., 'pitch': ...})
# 3. Feeds to disclaimer_runnable
# TODO: Assemble full_chain
full_chain = None

# Step 6: Test the execution
topic_input = "Time Management for Software Engineers"
print(f"Running pipeline for topic: '{topic_input}'...\n")

if full_chain:
    try:
        results = full_chain.invoke(topic_input)
        print("=== PIPELINE OUTPUT ===")
        print("OUTLINE:\n", results.get("outline"))
        print("\nMARKETING PITCH:\n", results.get("pitch"))
        print("=======================")
    except Exception as e:
        print("Pipeline execution failed. Error details:", e)
else:
    print("Initialize the TODO blocks to assemble the pipeline!")
