"""
MODULE 3 EXERCISE SOLUTION: Multi-Branch Composition using LCEL.
"""

import os
import sys
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableParallel, RunnableLambda

load_dotenv()

# Step 1: Initialize model
api_key = os.getenv("OPENROUTER_API_KEY")
if not api_key:
    print("ERROR: Please define OPENROUTER_API_KEY in your .env file.")
    sys.exit(1)

model = ChatOpenAI(
    openai_api_base="https://openrouter.ai/api/v1",
    openai_api_key=api_key,
    model_name="google/gemma-2-9b-it:free",
    temperature=0.7,
)

# Step 2: Build title generation step
title_prompt = ChatPromptTemplate.from_template("Generate a creative book title for a book about: {topic}")
title_chain = title_prompt | model | StrOutputParser()

# Step 3: Build parallel branches
outline_prompt = ChatPromptTemplate.from_template("Create a brief 3-chapter outline for the book titled: '{title}'")
marketing_prompt = ChatPromptTemplate.from_template("Write a one-sentence sales pitch targeting college students for the book: '{title}'")

outline_chain = outline_prompt | model | StrOutputParser()
marketing_chain = marketing_prompt | model | StrOutputParser()

# Combine outline and marketing into a parallel block
parallel_branches = RunnableParallel(
    outline=outline_chain,
    pitch=marketing_chain
)

# Step 4: Python function to inject disclaimer
def add_disclaimer(inputs: dict) -> dict:
    disclaimer = "\n\n[Disclaimer: All content generated by AI models]"
    return {
        "outline": inputs.get("outline", "") + disclaimer,
        "pitch": inputs.get("pitch", "") + disclaimer
    }

disclaimer_runnable = RunnableLambda(add_disclaimer)

# Step 5: Assemble the complete LCEL sequence
# We start by mapping the input topic string to the structure {'title': title_chain}
# then run parallel_branches, and finally append the disclaimer.
full_chain = (
    {"title": title_chain}
    | parallel_branches
    | disclaimer_runnable
)

# Step 6: Test the execution
topic_input = "Time Management for Software Engineers"
print(f"Running pipeline for topic: '{topic_input}'...\n")

try:
    results = full_chain.invoke(topic_input)
    print("=== PIPELINE OUTPUT ===")
    print("OUTLINE:\n", results.get("outline"))
    print("\nMARKETING PITCH:\n", results.get("pitch"))
    print("=======================")
except Exception as e:
    print("Pipeline execution failed. Error details:", e)
