version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: etl_postgres
    environment:
      POSTGRES_USER: etluser
      POSTGRES_PASSWORD: etlpassword
      POSTGRES_DB: weather_db
    ports:
      - "5433:5432"
    volumes:
      - etl_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etluser -d weather_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  etl_postgres_data:
