events {}

http {
    server {
        listen 80;

        location / {
            # In a docker-compose network, we can route traffic to other 
            # containers simply by using their service name!
            # Our python API service will be named 'api'.
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
