"""
MODULE 6 - MULTI-AGENT ORCHESTRATION: Agent Supervisor.

This script implements a collaborative multi-agent network where a central 
Supervisor node routes tasks dynamically to specialist worker nodes (Coder, Researcher)
before returning the final answer to the user.
"""

import os
import sys
from typing import Literal
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv(dotenv_path="../../.env")

api_key = os.getenv("OPENROUTER_API_KEY")
if not api_key:
    print("ERROR: Please define OPENROUTER_API_KEY in your .env file.")
    sys.exit(1)

from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langgraph.graph import START, END, MessagesState, StateGraph

# ------------------------------------------------------------------------------
# Step 1: Define Supervisor Routing Schema
# ------------------------------------------------------------------------------
class SupervisorRoute(BaseModel):
    """Routing decision payload generated by the supervisor."""
    next_step: Literal["researcher", "coder", "FINISH"] = Field(
        description="Select the next specialist worker to run. Choose 'FINISH' ONLY when the request is fully completed."
    )
    reason: str = Field(description="One sentence justification for selecting this next step.")

# ------------------------------------------------------------------------------
# Step 2: Initialize Chat Model and bind structured routing schema
# ------------------------------------------------------------------------------
# Llama 3 70B or Qwen 2.5 72B are best for structured routing and multi-agent coordination.
model = ChatOpenAI(
    openai_api_base="https://openrouter.ai/api/v1",
    openai_api_key=api_key,
    model_name="nvidia/nemotron-3-nano-30b-a3b:free",
    temperature=0.0,
)

# Bind structural parser output to model
supervisor_model = model.with_structured_output(SupervisorRoute)

# ------------------------------------------------------------------------------
# Step 3: Define Node Functions
# ------------------------------------------------------------------------------

def researcher_node(state: MessagesState) -> dict:
    """Specialist worker node: performs fact-finding and information searches."""
    print("\n>>> [Agent Node: Researcher] Performing web search mock...")
    messages = state["messages"]
    
    # Simple search helper prompt
    sys_prompt = (
        "You are an expert researcher. Retrieve facts, formulas, or documentation details "
        "requested by the user. Respond with a concise bulleted list of facts."
    )
    
    res = model.invoke([SystemMessage(content=sys_prompt)] + messages)
    print(f"Researcher output: {res.content[:100]}...")
    
    # Append message update prefixing the worker name
    return {"messages": [AIMessage(content=f"RESEARCHER REPORT:\n{res.content}", name="researcher")]}


def coder_node(state: MessagesState) -> dict:
    """Specialist worker node: drafts Python scripts and codes solutions."""
    print("\n>>> [Agent Node: Coder] Writing code...")
    messages = state["messages"]
    
    sys_prompt = (
        "You are an expert Python coder. Write clean, commented Python code to implement the task. "
        "Use the facts provided in the conversation history."
    )
    
    res = model.invoke([SystemMessage(content=sys_prompt)] + messages)
    print(f"Coder output: {res.content[:100]}...")
    
    return {"messages": [AIMessage(content=f"CODER OUTPUT:\n{res.content}", name="coder")]}


def supervisor_node(state: MessagesState) -> dict:
    """Manager node: evaluates the progress and routes to workers or FINISH."""
    print("\n>>> [Supervisor Node] Evaluating next actions...")
    messages = state["messages"]
    
    sys_prompt = (
        "You are a project manager supervising two worker nodes: 'researcher' and 'coder'.\n"
        "Your task is to review the conversation log and decide the next node to run.\n"
        "Rules:\n"
        "1. If the user query requires finding information (formulas, definitions, etc.) and it has not been done, run 'researcher'.\n"
        "2. If information has been found but code needs to be written, run 'coder'.\n"
        "3. If the final request is fully answered, run 'FINISH'."
    )
    
    # We call the structured supervisor model to retrieve next_step variable
    route_decision = supervisor_model.invoke([SystemMessage(content=sys_prompt)] + messages)
    print(f"Supervisor Decision: Next = {route_decision.next_step} | Reason = {route_decision.reason}")
    
    # Store decision inside a temporary message payload to pass along
    return {"messages": [AIMessage(content=route_decision.next_step, name="supervisor")]}

# ------------------------------------------------------------------------------
# Step 4: Assemble the StateGraph Builder
# ------------------------------------------------------------------------------
builder = StateGraph(MessagesState)

# Register nodes
builder.add_node("supervisor", supervisor_node)
builder.add_node("researcher", researcher_node)
builder.add_node("coder", coder_node)

# Set starting entry point
builder.add_edge(START, "supervisor")

# Once workers finish their task, they report back to the supervisor
builder.add_edge("researcher", "supervisor")
builder.add_edge("coder", "supervisor")

# Configure conditional edges from the supervisor node
def select_route(state: MessagesState) -> str:
    # Read the supervisor's last message to find the decision
    last_msg = state["messages"][-1]
    decision = last_msg.content.strip()
    
    if decision == "FINISH":
        return END
    return decision

builder.add_conditional_edges(
    "supervisor",
    select_route,
    {
        "researcher": "researcher",
        "coder": "coder",
        END: END
    }
)

# Compile graph
graph = builder.compile()
print("\nMulti-Agent Supervisor Graph Compiled successfully!")

# ------------------------------------------------------------------------------
# Step 5: Test Execution
# ------------------------------------------------------------------------------
query = (
    "Find the mathematical formula for the golden ratio, "
    "then write a short Python function that calculates it for N decimal places."
)

print(f"\n--- Running Multi-Agent Query: '{query}' ---")

# We stream execution events to observe the supervisor redirecting the flow
for event in graph.stream({"messages": [HumanMessage(content=query)]}):
    for node_name, state_update in event.items():
        print(f"\n[Transition: Node '{node_name}' finished]")
    print("-" * 50)

# Print final result details
final_state = graph.get_state({"configurable": {"thread_id": "temp"}})
print("\n=== FINAL GENERATED RESPONSE ===")
# Find the coder output message in state messages list
coder_msgs = [m for m in final_state.values.get("messages", []) if getattr(m, "name", "") == "coder"]
if coder_msgs:
    print(coder_msgs[-1].content)
else:
    print("Execution completed, but no coder report found.")
